[project]
name = "breef-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.22.0",
    "loguru>=0.7.3",
    "requests>=2.32.5",
    "urllib3>=2.5.0",
]
